sudo: required
services:
  - docker

before_install: 
  - docker build -t kartheek5/docker-react -f Dockerfile.dev .

script: 
   - docker run -e CI=true kartheek5/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-471112516953"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

