services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: kartheek5/composerfrontend
    container_name: composerfrontend
    ports:
      - "3000:3000"
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
  
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: kartheek5/composertest
    container_name: composertest
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    command: ["npm", "run", "test"]
   
